# Manually started action to build Python for Apple ARM Mac and upload to an artifact

name: Build ARM Python3 for Mac
on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
    paths-ignore:
    - '.github/**' # Ignore changes towards the .github directory

jobs:
  build:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.3.1'

    - name: Build Python3
      run: |
        uname -a
        brew update
        brew install bash libtool automake

        wget https://www.python.org/ftp/python/3.11.7/Python-3.11.7.tar.xz
        tar xvf Python-3.11.7.tar.xz
        cd Python-3.11.7
        
        # Build!
        ./configure --prefix=/tmp/python3
        make -j
        make install
        ls -al /tmp/python3

        tar cvf /tmp/python3.11.7-portable-darwin_arm64.tar /tmp/python3

    - name: Release
      uses: jason2866/action-gh-release@v1.3
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: /tmp/python3.12-portable-darwin_arm64.tar
