# Manually started action to build Python for AppleMac x64 and release

name: Build Python3 for Mac
on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
    paths-ignore:
    - '.github/**' # Ignore changes towards the .github directory

jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v4
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.1.0'

    - name: Build Python3
      run: |
        uname -a
        brew update
        brew install bash libtool automake

        wget https://www.python.org/ftp/python/3.11.7/Python-3.11.7.tar.xz
        tar xvf Python-3.11.7.tar.xz
        cd Python-3.11.7
        
        # Build!
        ./configure --prefix=/tmp/python3
        make -j
        make install
        ls -al /tmp/python3

        tar zcvf /tmp/python3.11.7-portable-darwin_arm64.tar.gz /tmp/python3

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: /tmp/python3.11.7-portable-darwin_arm64.tar.gz
